PREFIX=$$INSTALL_ROOT/usr
LIB_PREFIX=$$PREFIX/lib
CONTEXTKIT_SUBSCRIBER_PLUGIN_PATH=$$LIB_PREFIX/contextkit/subscriber-plugins
DATA_PREFIX=$$PREFIX/share
CONTEXTKIT_PROVIDER_CONTEXT_PATH=$$DATA_PREFIX/contextkit/providers
